### ISSUE TITLE
Picker条目数量多了之后，越往后错位越严重

### ISSUE THREAD

**Issue by 1009208036** [weui/weui#581]
Picker的条目多了之后，当前选中的会错位，越往后错位的越严重
![Markdown](http://p1.bqimg.com/1949/68ebb49c387eb045.png)
第一条还正常
![Markdown](http://p1.bqimg.com/1949/729128b743b15e45.png)
第五条开始有点偏移
![Markdown](http://p1.bqimg.com/1949/8afa865746ffda4a.png)
第十条偏移越来越严重
![Markdown](http://p1.bqimg.com/1949/680eff0e7b87b84f.png)
最后一条，完全偏移

**Comment by 1009208036** [comment]
找到解决方案了，把下图中的rowHeight改成33，bodyHeight改成 7*33就好了
![Markdown](http://p1.bqimg.com/1949/36cf6def9f3e7294.png)

**Comment by BearJ** [comment]
@1009208036 是这样的，目前只要字体大小发生改变，就会有这个问题。这是已知的一个bug~

**Comment by BearJ** [comment]
@1009208036 目前更建议使用这个来修复，在自己的样式里加入这段代码：
```css
.weui-picker__item{
    padding: 0;
    height: 34px;
    line-height: 34px;
}
```
