### ISSUE TITLE
建议在按钮disabled的样式加上禁止点击

### ISSUE THREAD

**Issue by ssshooter** [weui/weui#633]
```css
    .weui-btn_plain-disabled {
      cursor: not-allowed;
      pointer-events: none;
    }
```
